#174797543 Book an Accommodation
atlp-rwanda/script-heroes-bn-backend pull request #31
Opened 2020-10-15 14:05 UTC by jpirumvaa

### What does this PR do?
Allow users to book an accomodation

### Description of Task to be completed?

1. Pull the repo to get the project's latest version
2. Create a branch to work on
3. Select accommodation from the database.
4. Change` isVerified`  to be true and `userId` to be the id of a user who booked accommodation.
5. Validate User's Input
6. Write Tests
7. Add, commit, and push changes to GitHub

### How should this be manually tested?
Clone a repo, run `npm run dev` to run the project. After having a project running on a port using `localhost:PORTNO` to run the project in the browser. Go to `http://localhost:PORTNO/api/accommodation/book` . Make sure that you have `accomodationId` and `roomId` in the request's body. After sending the request, the message of success and the requester's information will be returned.
### What are the relevant pivotal tracker stories?
[#174797543](https://www.pivotaltracker.com/n/projects/2465784)

2020-10-20 15:13 UTC, b0nbon1 requested changes

2020-10-20 15:13 UTC, b0nbon1 commented on src/routes/accomodations/bookAccomodation.js
> +export default bookAccomodationRoute
add newline

2020-10-20 15:13 UTC, b0nbon1 commented on src/routes/accomodations/accomodation.js
> +    //[checkToken, checkAdmin],
remove commented line, if it's not being used

2020-10-20 15:13 UTC, b0nbon1 commented on src/routes/accomodations/accomodation.js
> +    //[checkToken, checkAdmin],
remove commented line, if it's not being used

2020-10-20 15:13 UTC, b0nbon1 commented on src/routes/accomodations/accomodation.js
> +    //[checkToken, checkAdmin],
remove commented line, if it's not being used

2020-10-20 15:13 UTC, b0nbon1 commented on src/routes/accomodations/accomodation.js
> +    //[checkToken, checkAdmin],
remove commented line, if it's not being used

2020-10-20 15:13 UTC, b0nbon1 commented on src/middlewares/validations/bookAccomodation.js
> +}
add newline

2020-10-20 15:13 UTC, b0nbon1 commented on src/controllers/bookAccomodation.js
> +}
add newline

2020-10-21 14:28 UTC, elvisiraguha commented on locales/en.json
> +	"Your are successfully loged in": "Your are successfully loged in",
Look out for these spacing changes, and add an empty line at the end of this file.

2020-10-21 15:22 UTC, dushimeemma approved these changes
Smell's good for me

2020-10-22 12:44 UTC, Junior-Adadie commented
May you change "accommodation" to "accomodation" or vice versa to keep the format of the codes consistent, also update the endpoint path in the PR description or the readMe file.

2020-10-22 13:08 UTC, Habinezajanvier approved these changes
I like it

2020-10-22 13:21 UTC, b0nbon1 approved these changes
Looks good

2020-10-22 13:22 UTC, merged