#174797528 Manage available requests
atlp-rwanda/script-heroes-bn-backend pull request #32
Opened 2020-10-16 08:27 UTC by ericus123

**What does this PR do?**

Display requests created by manager's direct report so that he can make a decision

**Description of Task to be completed?**
  - create a private route to display requests created by manager's direct report.
  - create a private route for a manager to make a decision on  requests created by his direct report.
  - create endpoint for making decision on requests created by his direct report.
  - validate decision route.

**How should this be manually tested?**

  - clone the repo `git clone https://github.com/atlp-rwanda/script-heroes-bn-backend.git`
  - switch your working directory `cd script-heroes-bn-backend`
  - checkout the branch `git checkout ft-manage-requests-for-approval-174797528`

**What are the relevant pivotal tracker stories?**

   [#174797528](https://www.pivotaltracker.com/story/show/174797528)

**Screenshots (if appropriate)**

2020-10-30 09:21 UTC, Habinezajanvier commented on locales/en.json
>  }
Please use the normal identation

2020-10-30 09:21 UTC, Habinezajanvier commented on test/controllers/manageRequests.test.js
> +      await User.create(manager2);
Couldn't it be possible to seed these managers and use them during testing

2020-10-30 10:02 UTC, jpirumvaa requested changes

2020-10-30 10:02 UTC, jpirumvaa commented on src/middlewares/auth.middleware.js
> +    }
Please check well this typo, `msghaha`

2020-10-30 12:43 UTC, ericus123 commented on src/middlewares/auth.middleware.js
> +    }
Yes,done now

2020-11-02 03:23 UTC, elvisiraguha approved these changes

2020-11-02 07:47 UTC, dushimeemma approved these changes
Smells good to me

2020-11-03 06:37 UTC, jpirumvaa commented on src/middlewares/auth.middleware.js
> +    }
Well done

2020-11-03 07:53 UTC, jpirumvaa approved these changes

2020-11-03 10:40 UTC, valens10 approved these changes

2020-11-03 13:52 UTC, merged