Fix login redirect to landing page
atlp-rwanda/script-heroes-bn-backend pull request #51
Opened 2020-12-08 14:10 UTC by florisng

#### What does this PR do?
User should be redirected to the landing page after login success
#### Description of Task to be completed?
- save token in cookie
- add a redirection to the landing page
#### How should this be manually tested?
- clone this repo `git clone https://github.com/atlp-rwanda/script-heroes-bn-backend`
- checkout the branch `git checkout fix-login-redirect-to-landing-page`
- run the app `npm run start`
- navigate to `http://localhost:3000/auth/login`
- Insert the credentials
- When login success you will be redirected to the landingPage
#### What are the relevant pivotal tracker stories?
[#175973595](https://www.pivotaltracker.com/story/show/175973595)

2020-12-10 15:08 UTC, jpirumvaa requested changes

2020-12-10 15:08 UTC, jpirumvaa commented on src/routes/facebookRoutes.js
> +    res.redirect('/');
Redirect to the front-end's landing page instead of the backend one.

2020-12-10 15:08 UTC, jpirumvaa commented on src/routes/googleRoutes.js
> +    res.redirect('/');
Redirect to the front-end's landing page instead of the backend one.

2020-12-11 09:19 UTC, valens10 approved these changes

2021-01-11 14:53 UTC, merged