chore(sequelize): setup sequelize
atlp-rwanda/script-heroes-bn-backend pull request #9
Opened 2020-09-19 20:44 UTC by valens10

#### What does this PR do?
configure sequelize to be used as our ORM on the API.
#### Description of Task to be completed?
- install Sequelize and Sequelize-cli
- setup .sequeliceC file
-configure squelize
-Set up the migrations and models structure
#### How should this be manually tested?
- Clone the repo `git clone https://github.com/atlp-rwanda/script-heroes-bn-backend.git`
- Switch your working directory `cd script-heroes-bn-backend`
- Checkout the branch `git checkout ch-setup-sequelize-#174797509`
- Create a .squelizeC file in the project root directory
- Configure the database/config.js file the required dtata
- Creating first Model (and Migration) with `sequelize model:generate --name User --attributes firstName:string,lastName:string,email:string`
- Running Migrations with `sequelize db:migrate`
-Creating First Seed with `sequelize seed:generate --name demo-user`
-Running Seeds with `Running Seeds`
#### What are the relevant pivotal tracker stories?
[#174797504](https://www.pivotaltracker.com/story/show/174797504)

2020-09-20 07:31 UTC, dushimeemma approved these changes
please fix some hound ci violations

2020-09-20 08:47 UTC, elvisiraguha requested changes
@valens10 try to reduce these HoundCI warnings please.

2020-09-20 09:25 UTC, valens10 commented
> @valens10 try to reduce these HoundCI warnings please.

This is noted.

2020-09-20 18:34 UTC, Junior-Adadie commented on src/database/models/index.js
> +const config = require(__dirname + '/../config.js')[env];
Try removing this .env code, the one working on env will add it in if necessary

2020-09-20 18:48 UTC, Junior-Adadie commented on src/database/models/item.js
> +'use strict';
@valens10 Try removing the 'use strict' expression, I don't think it's required there

2020-09-21 08:35 UTC, elvisiraguha approved these changes

2020-09-22 12:04 UTC, kipropbrian commented
Hey @valens10 you can ignore the database folder from hound violations and complaints.

2020-09-22 16:35 UTC, Habinezajanvier approved these changes
good

2020-09-22 19:09 UTC, Junior-Adadie approved these changes

2020-09-22 22:44 UTC, kipropbrian commented
Some feedback. 
 - Sequelize and sequelize-cli should be in package.json 
- Your Readme has unnecessary things. It's like you copy pasted that from somewhere. Make it short and to the point. Too many stories do not help. 
- Remove your username from the configs. Do not use `valens` use `admin` or another name.
- sequelize-cli db:migrate does not work.

2020-09-23 15:16 UTC, merged